import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navigation from './components/navigation/navigation.component'
import Footer from './components/footer/footer.component'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Portfolio Site',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col min-h-screen justify-between w-full'>
        <div className='h-[385px] bg-teal-50 pt-[34px]'>
          <Navigation/>
          <main className='lg:px-[163px] px-[20px]'>
          {children}
          </main>
          
        </div>
        <Footer/>
        </div>
      </body>
    </html>
  )
}
